### ISSUE TITLE
Create SC test data

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#11]
### Background Information

Include SC.TEST for eye indicator

**Comment by eriola11** [comment]
Hi @barnett11 @palmenl I will create a SC dataset where Study Eye information will have  **SCTESTCD=STUDYEYE**  Let me know if you disagree with the choice SCTESTCD. @palmenl  please take this into consideration when you create the functions to extract this info in ADaMs

**Comment by barnett11** [comment]
Hi @eriola11 - SCTESTCD in our standards would be equal to "FOCID" for selection

**Comment by eriola11** [comment]
Thanks @barnett11  for pointing this out. I don't know why current studies in PDS are using SC.STESTCD =STUDYEYE (I let the study SPA know) but I will use FOCID as per standard

**Comment by manciniedoardo** [comment]
@eriola11 Tagging myself in this as the function `derive_var_studyeye` that I wrote for issue #9 can be used to test this data.
