### ISSUE TITLE
General Issue: Add AFEYE to ADBCVA and ADOE templates

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#133]
### Background Information

Feedback from testers is that the variable `AFEYE` is useful to have in ADOE and ADBCVA, at the very least for mapping purposes. Could we add it to our template programs? Can `derive_var_afeye` be used here?

**Comment by aldrichsalva** [comment]
Updated adoe and adbcva templates to add AFEYE derivation. Changed lookup tables to only need AFEYE and OETESTCD as by variables removing  the need for STUDYEYE and OELAT.

Upon updating the vignettes the respective vignettes, I noticed that adoe might be unfinished. It seems to stop at the merge between adoe and adsl. Should this be updated similar to adbcva which sees the complete creation of the dataset?

![image](https://github.com/pharmaverse/admiralophtha/assets/126184896/7010c15e-7c7c-4971-8528-820d0bf877c3)

![image](https://github.com/pharmaverse/admiralophtha/assets/126184896/6e267dff-72f6-4809-b0c8-453103c235d2)
