### ISSUE TITLE
General Issue: Update to derived parameters in ADBCVA template

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#137]
### Background Information

When deriving LogMAR Score Parameters: DTYPE should be missing in this case as new parameters were created (not derived records within the same parameter).
Also, as a general rule when a new record is derived from a single record in the dataset, any variable values from the original record that do not change and that make sense in the context of the new record (e.g., --SEQ, VISIT, VISITNUM, --TPT, covariates, etc.) should be retained on the derived record. So, VISIT, VISITNUM, OEDY and OEDTC shouldn't be set to missing afterwards.

**Comment by ukey1025** [comment]
Hi @manciniedoardo,

I could modify LogMAR score related codes in ADBCVA template. However, I am not sure about following problem.
> So, VISIT, VISITNUM, OEDY and OEDTC shouldn't be set to missing afterwards.
The following codes set to missing for VISIT, VISITNUM, OEDY, and OEDTC. Would I delete and/or modify here?
```
  # Set SDTM variables back to missing for derived parameters
  mutate(
    VISIT = ifelse(PARAMCD %in% c("SBCVALOG", "FBCVALOG"), NA_character_, VISIT),
    VISITNUM = ifelse(PARAMCD %in% c("SBCVALOG", "FBCVALOG"), NA, VISITNUM),
    OEDY = ifelse(PARAMCD %in% c("SBCVALOG", "FBCVALOG"), NA, OEDY),
    OEDTC = ifelse(PARAMCD %in% c("SBCVALOG", "FBCVALOG"), NA_character_, OEDTC)
```

**Comment by manciniedoardo** [comment]
Hi @ukey1025 - correct, that bit of code you quoted needs to be modified, so that the values for VISIT, VISITNUM, OEDY and OEDTC for the new parameters are the retained values from the relevant old parameters.
