### ISSUE TITLE
Share primary and secondary endpoints for discussion

### ISSUE THREAD

**Issue by hiren8484** [pharmaverse/admiralophtha#2]
### Background Information

Test

**Comment by barnett11** [comment]
As discussed as a starting point, we recently across a few projects have seen:

- Change from baseline in BCVA (as measured on the ETDRS chart at a starting distance of 4 meters) at X timepoint / Over Time
- Mean change in the GA area from baseline to X timepoint as measured by fundus autofluorescence (FAF)
- Proportion of patients with a >=2-step DRS improvement from baseline on the ETDRS DRSS at X timepoint / Over time
- Proportion of patients gaining >=15, >=10, .>=5, or >=0 letters in BCVA from baseline at X timepoint / Over time
- Proportion of patients avoiding a loss of >=15, >=10>=5, or >=0 letters in BCVA from baseline at X timepoint / Over time
- Proportion of patients gaining >=15 letters or achieving BCVA of >=84 letters at X timepoint / Over time
- Proportion of patients with BCVA Snellen equivalent of 20/40 or better at X timepoint / over time
- Proportion of patients with BCVA Snellen equivalent of 20/200 or worse over time at X timepoint / over time
- Proportion of participants with BCVA ≥ 69 letters (20/40 Snellen equivalent), or ≥ 84 letters (20/20 Snellen equivalent) over time
- Proportion of patients with a >=3-step DRS improvement from baseline on the ETDRS DRSS over time
- Change from baseline in CST / CPT / CFT at X timepoint / Over time
- Proportion of patients with absence of DME (CST <325um) over time
- Proportion of patients with absence of intraretinal fluid and subretinal fluid over time
- Change from baseline in NEI VFQ-25 composite score over time
- Incidence and severity of ocular adverse events or non-ocular events

**Comment by wholmes57** [comment]
Further potential endpoints to consider:

- Proportion of patients with absence of UME (CST <325um) at X timepoint / over time
- Time to rescue treatment
- Number and type of rescue treatments received 
- Proportion of participants with a ≥4 point improvement from baseline in the NEI VFQ-25 composite score at X timepoint / over time
- Change from baseline in the NEI VFQ-25 Near Activities, Distance Activities and Driving subscale scores at X timepoint / over time
- Change from baseline in the NEI VFQ-25 General Vision, Ocular Pain, Social Functioning, Mental Health, Role Difficulties, Dependency, Color Vision and Peripheral Vision subscale scores at X timepoint / over time
- Change from baseline in the area of ischemic non‑perfusion at X timepoint / over time

**Comment by traceyxw** [comment]
Rate of Patients Developing a Vision Threatening Complication (Defined as PDR or ASNV), or CI-DME (Defined as CST >= 325 mm on SD-OCT) over time (PDR = proliferative diabetic retinopathy; ASNV = anterior segment neovascularization)
