### ISSUE TITLE
Create function for Study Eye Location: ADSL.STUDYEYE

### ISSUE THREAD

**Issue by hiren8484** [pharmaverse/admiralophtha#20]
Create function for Study Eye Location e.g. ADSL.STUDYEYE (based on SC test data from issue 11)

**Comment by manciniedoardo** [comment]
Hi @hiren8484 I think this is covered by #9 which is now closed.

**Comment by hiren8484** [comment]
Thanks @manciniedoardo I realised after assigning it! Thanks for spotting, will close this off.
