### ISSUE TITLE
Create function for Affected Eye: ADCM.AFEYE

### ISSUE THREAD

**Issue by hiren8484** [pharmaverse/admiralophtha#21]
Create function for Affected Eye: ADCM.AFEYE

**Comment by manciniedoardo** [comment]
Hi @hiren8484, I think this is equivalent to issue #10 which @palmenl is working on?

**Comment by hiren8484** [comment]
Thanks @manciniedoardo I realised after assigning it, that Lucy was working on the function that would be applicable across the different ADaMs. Thanks for spotting, will close this off.
