### ISSUE TITLE
Chrome tab icon shows pharmaverse hex and generic title rather than admiralophtha hex and title

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#225]
### Please select a category the issue is focused on?

Other

### Let us know where something needs a refresh or put your idea here!

See admiralonco
![image](https://github.com/pharmaverse/admiralophtha/assets/53403957/b1999337-eace-4bf7-b80f-f4b741c60a38)
Compared to admiralophtha
![image](https://github.com/pharmaverse/admiralophtha/assets/53403957/234cddb7-3ab8-4ecd-a584-0a6d1c6570b6)

**Comment by manciniedoardo** [comment]
@ukey1025 are you interested in taking this on?

**Comment by ukey1025** [comment]
Hi @manciniedoardo, sorry for my delay response. I will try this issue. Thanks.

**Comment by manciniedoardo** [comment]
@ukey1025 is there any update on this? release is next week, would be good to get this out of the way before then.

**Comment by ukey1025** [comment]
Hi @manciniedoardo, I have sent you a pull request - please review it. Thanks.
