### ISSUE TITLE
Documentation & Templates: Make subject keys consistently flexible

### ISSUE THREAD

**Issue by rossfarrugia** [pharmaverse/admiralophtha#226]
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

There's some examples in the vignettes and the templates where `STUDYID` or `USUBJID` are still being called usually in `by_vars` instead of `get_admiral_option("subject_keys")`. See https://pharmaverse.github.io/admiral/reference/#admiral-options.

For example see `inst/templates/ad_adoe.R` or `vignettes/advfq.Rmd`.

Also in assertion check call in `R/derive_var_bcvacritxfl.R`.

FYI @manciniedoardo

**Comment by aldrichsalva** [comment]
I added set_admiral_options() right below the library functions in each of the templates based on the example in https://pharmaverse.github.io/admiral/reference/set_admiral_options.html.
![image](https://github.com/pharmaverse/admiralophtha/assets/126184896/723a9f56-251e-4858-b504-19701d6ba71f)

Would the placement of the function be the same for vignettes?
![image](https://github.com/pharmaverse/admiralophtha/assets/126184896/2ca94200-f1d7-4038-aab6-f84079532a20)

**Comment by rossfarrugia** [comment]
@aldrichsalva the admiral package already defaults to these values so you don't need to ever set them in the templates (unless a user ever wanted to change these). you could follow this PR to guide on the updates needed, but bear in mind its still in progress so see the review comments: https://github.com/pharmaverse/admiral/pull/2452

**Comment by manciniedoardo** [comment]
thanks @rossfarrugia - @aldrichsalva I believe for admiralophtha you'd just have to replace any mentions like this:
```
  derive_vars_merged(
    dataset_add = adsl,
    new_vars = adsl_vars,
    by_vars = exprs(STUDYID, USUBJID)
  )
```
with something like this:
```
  derive_vars_merged(
    dataset_add = adsl,
    new_vars = adsl_vars,
    by_vars = get_admiral_options("subject_keys")
  )
```
with the code a little more complex in the case that the `by_vars` encompass more variables than just the subject keys. See the PR that Ross linked for some examples there.

**Comment by rossfarrugia** [comment]
I made a similar PR for admiralonco earlier for this as FYI: https://github.com/pharmaverse/admiralonco/pull/285/files - there's a couple of minor other pieces updated there too, but in the most part its examples like Edoardo shared above. To find the impacts I used a search on the github repo for `USUBJID` and then worked from there.

**Comment by rossfarrugia** [comment]
Also I realised that for the admiralroche (closed source) templates we did choose to include the `set_admiral_options()` call so that might have caused confusion here. I guess that decision was as we have one team using this tool that do likely need to change this option so we made it more visible there as a reminder, but the same wasn't deemed needed in admiral core so better we keep the open source packages consistent.

**Comment by manciniedoardo** [comment]
@aldrichsalva any chance you can take a stab at this today, so that we can release tomorrow? otherwise i can take over form you.

**Comment by aldrichsalva** [comment]
@manciniedoardo apologies for the delay! Please take over if that is ok.
