### ISSUE TITLE
Update ADBCVA vignette, template to use new {admiral} AVALCAT derivation function

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#244]
### Background Information

Currently there is nothing specific in {admiral} for AVALCAT derivation so ADBCVA template and vignette just go about it using tidyverse tools. This will change once the functionality is added to {admiral} - [see here](https://github.com/pharmaverse/admiral/issues/2480).

### Definition of Done

Update template and vignette to use new {admiral} function.

**Comment by steventing12** [comment]
Used derive_vars_cat() to derive AVALCA1N and AVALCAT1, replacing look-up table with derive_vars_merged(). However, the input expression is still duplicating conditions for SBCVA and FBCVA as a combining expressions doesn't yield the same structure.

**Comment by manciniedoardo** [comment]
Can you please make a pull request with your proposed changes? That way I can review code/changes and propose amendments.
