### ISSUE TITLE
Supersede `derive_var_bcvacritxfl()` and update vignettes/templates that use it

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#247]
### Background Information

With the advent of [admiral::derive_vars_crit_flag()](https://pharmaverse.github.io/admiral/dev/reference/derive_vars_crit_flag.html) there is less of a need for `admiralophtha::derive_var_bcvacrtixfl()`. The latter should be superseded, in line with the {admiral} family's policy to not make many breaking changes post 1.0 releases.

### Definition of Done

- [x] `derive_var_bcvacritxfl()` superseded. See [here](https://github.com/pharmaverse/admiral/blob/main/R/derive_var_dthcaus.R) for an example of a superseded function from {admiral}.
- [x] templates/vignettesalso updated to not use it anymore and use `derive_vars_crit_flag()`, possibly in conjunction with `call_derivation()`.

**Comment by steventing12** [comment]
Used call_derivation with derive_vars_crit_flag() to generate CRITy conditions and CRITyFL flags, superseding derive_var_bcvacritxfl()

**Comment by manciniedoardo** [comment]
Can you please make a pull request with your proposed changes? That way I can review code/changes and propose amendments.
