### ISSUE TITLE
Create workflow for ADBCVA and then create/reuse existing function for BCVA (Best Corrected Visual Acuity Score) endpoint

### ISSUE THREAD

**Issue by hiren8484** [pharmaverse/admiralophtha#27]
Create function for BCVA - Best Corrected Visual Acuity Score (incorporating both Study Eye and Fellow Eye) endpoint.

Derivation is provided with Box.com folder, under "Ophtha ADaM specs" within ADOE Parameters tab and also "Ophtha_ADaM_Specifications_Novartis" under ADVA. 

Recommendation is to use Criteria flags e.g. CRIT1, CRIT1FL etc. Note: The programming style should follow the Novartis specs (which are using criteria flags) but for now, please see the Roche derivations in the ADOE Parameters tab to pick up the change from baseline categories. 

It may be worth creating "AdmiralOphtha" specs so that this is the specifications file we use as a team.

**Comment by traceyxw** [comment]
Just adding some notes on potential functions from Admiral to create change from baseline variables:

- Derive Change from Baseline (CHG, PCHG) (https://pharmaverse.github.io/admiral/articles/bds_finding.html#bchange)
- Derive Baseline (BASETYPE, ABLFL, BASE, BASEC, BNRIND) (https://pharmaverse.github.io/admiral/articles/bds_finding.html#baseline)
- Derive Results (AVAL, AVALC) (https://pharmaverse.github.io/admiral/articles/bds_finding.html#aval)

**Comment by wqrena** [comment]
Use the existing workflow for dataset. Ref: https://exbpbox.ent.box.com/folder/135158344442?s=wbsc3rkhbyxdvuua1csh4sez5n6nwl7n
