### ISSUE TITLE
Create Workflow for ADIOP and then create/use existing function for IOP (Intraocular Pressure) endpoint

### ISSUE THREAD

**Issue by hiren8484** [pharmaverse/admiralophtha#28]
Create a function for IOP - Intraocular Pressure endpoint (for Study and Fellow Eye). Please follow Novartis specs e.g. ADIOP and use of the criteria flags to capture the different categories.

It may be worth creating/adding to "AdmiralOphtha" specs so that this is the specifications file we use as a team.

**Comment by traceyxw** [comment]
I am looking into functions from Admiral to create the criteria flags:

- Derive Categorization Variables (AVALCATx) (https://pharmaverse.github.io/admiral/articles/bds_finding.html#cat)

**Comment by traceyxw** [comment]
Adding link to Novartis specs on ADIOP for fast reference: https://exbpbox.ent.box.com/file/1027069841691?s=436gxjsmvq5hmrwbelazysez9hwg8b90
