### ISSUE TITLE
Agree on test data needed

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#3]
### Background Information

Potential test data needed:
OE
SC (for study eye selection - confirm this is general use)
AE (for eye laterality)

**Comment by barnett11** [comment]
Will test data be within admiral.test, or as it is Ophtha specific does it go to admiralophtha?

**Comment by millerg23** [comment]
Ideally, test data and the program to create it would be live in admiral.test.  If its preferable, the optha team could initially create test data within the optha area, and then we (or I) could move it over.
Please see https://github.com/pharmaverse/admiral.test/tree/main/inst/data_scripts to get an idea of how some data was created for Onco.

**Comment by wholmes57** [comment]
Potentially need test data for rescue treatments, although I'm not sure which domain this would come under, as standard

**Comment by aliceBIU** [comment]
yes, it would be nice to have intercurrent events data. In some of the ophtha studies we even created ICE ADaM datasets (ADICE & ADICESUM) to support the efficacy analysis. Instead of using SDTM data, we used mostly ADaM datasets, e.g. ADSL, ADCM, ADPR, to create these two because some of the flags need to be derived at ADaM level. 
A question to the team: Are we going to add ICE datasets to our scope?

**Comment by barnett11** [comment]
Thanks @aliceBIU -  I think we may need to wait for the estimand guidance to mature a little more before pursuing this in this space, and even then it would be a general admiral approach rather than Ophtha specific. For now I'd recommend we keep just the known standards in scope, and hopefully later on see how estimands are incorporated.

**Comment by eriola11** [comment]
> Ideally, test data and the program to create it would be live in admiral.test. If its preferable, the optha team could initially create test data within the optha area, and then we (or I) could move it over. Please see https://github.com/pharmaverse/admiral.test/tree/main/inst/data_scripts to get an idea of how some data was created for Onco.

Hi @millerg23 , the link is not working. Are you able to help. Thanks

**Comment by eriola11** [comment]
Hi @millerg23 , Where should the test data stored?

**Comment by millerg23** [comment]
Hi @eriola11 sorry for not replying sooner, here is the relevant link:
https://github.com/pharmaverse/admiral.test/blob/main/README.md

Ideally the test data would be stored in `admiral.test`.
