### ISSUE TITLE
Discuss and share general ADaM conventions (outside of Ophth assessments) + spec sharing

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#4]
### Background Information

Indicator of eye selected for study - What are we using in ADSL to denote this (if ADSL?)
Indicator of eye within Occurrence datasets - Eg. in ADAE/ADMH etc. to denote Study or Fellow Eye - What var do we use?

**Comment by barnett11** [comment]
In our studies, we currently use the below,
ADSL.STUDYEYE - This is used to indicate LEFT/RIGHT/BILATERAL as the study selected eye
ADAE.AFEYE - This is used to decode AELAT (normally "LEFT", "RIGHT") to indicate either "STUDY EYE" or "FELLOW EYE"

**Comment by palmenl** [comment]
Similarly for ADEX we have ADEX.AFEYE ('Study Eye' or 'Fellow Eye') coming from EXLAT ('LEFT' or 'RIGHT')

**Comment by manciniedoardo** [comment]
We also have this as above for ADPR (PRLAT used in the derivation for AFEYE in ADPR). Furthermore if we are producing ADMH we might want to consider targeted ophtha medical history terms with MHLAT.

**Comment by wqrena** [comment]
In our study (PDS), 
ADSL.STUDYEYE is used to indicate the selected study eye. The info is from SDTM.SC mapped from the eCRF Form: Study Eye Selection.

AFEYE is used in ADAE, ADEX, ADCM, ADPR, ADMH to indicated the affected eye based on ADSL.STUDYEYE, xxLOC and xxLAT
