### ISSUE TITLE
General Issue: ADVFQ Research

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#47]
### Background Information

Look through the ADBCVA datasets on ophthalmology studies to which you have access. Please leave comment(s) here detailing ophthalmology-related:

common derivations (that maybe take a lot of repetitive code)
custom macros
common variable derivations
common endpoint derivations
common derived parameters
Aim is to find out what functions/code we can provide in {admiralophtha} to streamline the production of an ADBCVA dataset in R. Then we can make issues for each piece of programming work and start implementing it!

**Comment by manciniedoardo** [comment]
Adding @ritika-aggarr to gather info about Novartis approach to Ophtha questionnaires.

**Comment by linacrer** [comment]
- Assigning subscale categories to parcat2
- recoded results based on parameters
- deriving subscale scores
