### ISSUE TITLE
General Issue: Move test SDTM datasets and programs to admiral.test package

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#48]
### Background Information

NOTE: `admiral_ae` needs to be renamed to `admiralophtha_ae` (so the actual program that generates the dataset needs a small update, and the dataset needs to be regenerated too) so that they have the correct name.

**Comment by millerg23** [comment]
Tickets created in `admiral.test.` for each of the SDTMs to be updated/created.

**Comment by manciniedoardo** [comment]
HI @millerg23 is this all completed now? Can we remove programs/datasets from devel?

**Comment by millerg23** [comment]
AE and OE are there (in `devel` branch). SC should be there very shortly, just waiting on approval. That just leaves EX, I will look to get that moved early next week.
If possible can you check AE and OE, you may need to re-install admiral.test package to get latest version.

**Comment by manciniedoardo** [comment]
@millerg23 Yep can see AE and OE correctly. Just one note, `AELAT` is missing a label in AE so maybe it should be added?
