### ISSUE TITLE
Read and familiarise with admiral style guides / approach

### ISSUE THREAD

**Issue by barnett11** [pharmaverse/admiralophtha#5]
### Background Information

https://pharmaverse.github.io/admiral/articles/contribution_model.html
https://pharmaverse.github.io/admiral/articles/programming_strategy.html

### Definition of Done

- [x] Tim
- [ ] Hiren
- [ ] Ashish
- [x] Rena
- [x] Tracey
- [ ] Ajay
- [ ] Iris
- [x] Eriola
- [x] Pierre
- [x] Yuki
- [x] Ritika
- [ ] Arpita
- [x] Edoardo
- [x] Lucy
- [ ] Arun
- [x] Will

**Comment by Pierre-Wallet** [comment]
Hi @barnett11 ,
I am currently not able to edit the above issue. Is it related to right permission?
