### ISSUE TITLE
Create VFQ test data

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#52]
Create test data for Visual Functioning Questionnaire in a qs domain. We definitely have some studies in Roche that use this however not sure about Novartis (@ritika-aggarr @ukey1025).

**Comment by ritika-aggarr** [comment]
We do have VFQ data flowing into QS domain for the ophtha studies at Novartis. @manciniedoardo is there any specification for the VFQ test data? Or perhaps list of expected variables?
