### ISSUE TITLE
Unable to read admiral_oe.rds dataset 

### ISSUE THREAD

**Issue by NandiniRThampi** [pharmaverse/admiralophtha#54]
### What happened?

Trying to load the admiral_oe.rds dataset gives the following error:
`Error in readRDS("~/admiralophtha/inst/extdata/admiral_oe.rds") : unknown input format` 

This may be due to the function used to store the dataset in oe.R - `save(admiral_oe, file = "inst/extdata/admiral_oe.rds", compress = "bzip2")` 

Solution to use in oe.R instead: `saveRDS(admiral_ae, "inst/extdata/admiral_oe.rds")`

**Comment by manciniedoardo** [comment]
Closing issue
