### ISSUE TITLE
Documentation:  Make sure readme file is ready for release 0.1.0

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#68]
### Let us know where something needs a refresh or put your idea here!

Sense check and make sure format is ok. Does anything else need to be added?

**Comment by jiegaoo** [comment]
Hi Edoardo,
Please kindly find below for my review comments.
1. the link [{admiral} References and Documentation (https://pharmaverse.github.io/admiral/devel). doesn't work, page is 404 not found.
2. I am wondering if a Description or Purpose part is nice to have at the beginning of this page?
3. under the scope section, should we add currently available domains under it?

**Comment by manciniedoardo** [comment]
Hi @jiegaoo thanks for your review.  The next step would be for you to make a branch and make these updates!

1. Could you please find the 
2. Love the idea, let's do it.
3. same.

Let me know if you have any questions or need any help.

**Comment by manciniedoardo** [comment]
@jiegaoo - thanks for your updates. as discussed, upon reflection the "Expectations" section in the readme is just repeating material exposed in the "Purpose" section, so I think it can be removed. Please could you also updated the "Purpose" section to say "To provide a complementary (to admiral) toolbox that enables users to develop ophthalmology disease area _datasets and endpoints_.

You can do the updates in your existing issue branch (no need to create a new one) as long as you bring it up to speed with what is in `devel` by running `git merge devel` in the console after having pulled `devel`. Please also re-build the site once done.
