### ISSUE TITLE
Create ophtha-specific ADSL template

### ISSUE THREAD

**Issue by jj1994** [pharmaverse/admiralophtha#8]

**Comment by eriola11** [comment]
The idea here is to see how the admiral template for creating ADSL will need to be update for Opth studies. 
e.g - function creating treatment start/end dates (TRTSTDT/TRTEDT) from EX should consider only valid doses in **STUDY EYE**
      - add code for creating STUDYEYE and ELIGEYE variables in ADSL

**Comment by manciniedoardo** [comment]
Dropping myself from this issue in case someone wants to pick it up while i work on other issues for the sprint - there is already a branch for it.

**Comment by manciniedoardo** [comment]
Suggesting one programmer as this is half done.
