### ISSUE TITLE
Updata VFQ test data in admiral.test so that not all answers to questions are the same.

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralophtha#94]
To be done in admiral.test's Q2 2023 release.

**Comment by jiegaoo** [comment]
Hi Ritika, 

Thanks for generating the vfq.R, I've checked the code and have several questions as follows:

1. it seems this questionnaire contained several optional parts, and currently our dataset only contain the mandatory part, should we update to include the remaining part? 
2. And the QSTESTCD is not consistent with the spec, e.g. the QSTESTCD for following questions are :
- VFQ115A	Never Driven or Given Up Driving
- VFQ115B	Main Reason You Gave Up Driving
- VFQ115C	Difficulty Driving During Daytime
but in the code we named them as VFQ16, VFQ17, VFQ18 respectively.
I am not sure whether the dataset should be strictly complied with the spec or the basic structure is okay?(although currently advfq.R filtered the dataset to only include VFQ1-VFQ4, I am not sure if the template code will be updated in future to include all QSTESTCD, if not, please ignore above 2 questions.
3. the QSORRES is not all in consistency with the results options in questionnaire, for example for VFQ1 and VFQ2, questionnaire contain 5 options and 6 options respectively, but in the vfq.R both contain 5 options.

**Comment by jiegaoo** [comment]
will leave this admiral.test update to next release, and we will create a temporary admiralophtha_qs.rda for current usage.
